### ISSUE TITLE
gateway state

### ISSUE THREAD

**Issue by h0bb3** [srcfl/srcful-gateway#227]
There is a bit of a caveat when adding a new inverter via the settings file which was the intended way of doing things. In essence we would need to know if the inverter has been opened before (so we can start a perpetual task) or if the inverter is new and an ordinary open device task should be run.

We could solve this by having a flag (or counter) for how many times an inverter has been opened. I'm actually think this could be a good idea to have also in the configurator UI. Maybe even a time when the device was added and last connected to would be good to have.

Come to think of an UI would need some way of getting the status of the inverter... much as we do via the REST api... maybe send the commands this way also... eg. just build a new communication channel via the graphql subscriptions... this way we would not need to build something special for the status... the rest api is available via the qraphq api...

**Comment by h0bb3** [comment]
or we can simply e.g. serialize the blackboard to some state and have a state subKey...

**Comment by h0bb3** [comment]
Ok the latest iteration would be to have a state subKey, a request subKey for sending commands to the gateway compare to e.g. POST and a response subKey. The settings will be more or less a "read only ting" for the gateway to store settings.

State would contain everything e.g. crypto info, wifi ssids, devices (and their state).

**Comment by davmoz** [comment]
Saving several device configurations and loading them should be possible as of 7f8c9b5f727ceefb65775fa11adc31860620c1a4.

**Short:**
A modbus configuration is saved for every _unique_ (by MAC/SN) successful connection. The configurations are saved in the `state` (saved in RAM) and `settings` (saved in Backend).

If the gateway reboots, the `state` is wiped, but the gateway fetches the settings from backend and tries to open every single saved configuration and the `state` updates accordingly. 

> Maybe even a time when the device was added and last connected to would be good to have.

I like this, as it would help us keep the track of configurations and help decide what to remove and what to keep. The user should also be able to _reset_ the `settings`, but that's for another issue. 

Closing this since most of the issues mentioned here are implemented, apart from the UI stuff...
